version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: on-failure
    environment:
      POSTGRES_DB: listy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/db/migration/V1_0_0__create_listy_schema.sql:/docker-entrypoint-initdb.d/V1_0_0__create_listy_schema.sql

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    image: listy:latest
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/listy
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456