INSERT INTO listy.comment (author, comment, date) VALUES ('Arda', 'Siparişim zamanında geldi, çok memnunum.', '2023-03-01');
INSERT INTO listy.comment (author, comment, date) VALUES ('Ardam', 'Ürün kalitesi beklediğimden iyiydi.', '2023-03-02');
INSERT INTO listy.comment (author, comment, date) VALUES ('Tolga', 'Müşteri hizmetleri harikaydı, teşekkür ederim.', '2023-03-03');
INSERT INTO listy.comment (author, comment, date) VALUES ('LEMİNA', 'Fiyat-performans açısından çok başarılı bir alışveriş oldu.', '2023-03-04');
INSERT INTO listy.comment (author, comment, date) VALUES ('Arda', 'Web sitesi kullanımı kolay ve hızlı bir alışveriş deneyimi sundu.', '2023-03-05');
INSERT INTO listy.comment (author, comment, date) VALUES ('Ardam', 'Ürün açıklaması ve görseller gerçeği yansıtıyordu.', '2023-03-06');
INSERT INTO listy.comment (author, comment, date) VALUES ('Tolga', 'Paketleme özenliydi, üründe herhangi bir hasar yoktu.', '2023-03-07');
INSERT INTO listy.comment (author, comment, date) VALUES ('LEMİNA', 'Teslimat süresi beklediğimden daha hızlı gerçekleşti.', '2023-03-08');
INSERT INTO listy.comment (author, comment, date) VALUES ('Arda', 'Alışveriş deneyimim genel olarak olumlu geçti.', '2023-03-09');
INSERT INTO listy.comment (author, comment, date) VALUES ('Ardam', 'Ürünün kalitesi ve dayanıklılığı beni tatmin etti.', '2023-03-10');

INSERT INTO listy.comment (author, comment, date) VALUES ('Tolga', 'Sipariş sonrası destek hizmeti hızlı ve etkiliydi.', '2023-03-11');
INSERT INTO listy.comment (author, comment, date) VALUES ('LEMİNA', 'Ürünü inceledikten sonra karar verdim, memnunum.', '2023-03-12');
INSERT INTO listy.comment (author, comment, date) VALUES ('Arda', 'Kargo sorunsuz ve zamanında teslim edildi.', '2023-03-13');
INSERT INTO listy.comment (author, comment, date) VALUES ('Ardam', 'Fiyatlandırma oldukça rekabetçiydi.', '2023-03-14');
INSERT INTO listy.comment (author, comment, date) VALUES ('Tolga', 'Ürün beklentilerimi fazlasıyla karşıladı.', '2023-03-15');
INSERT INTO listy.comment (author, comment, date) VALUES ('LEMİNA', 'Müşteri hizmetleri sorularıma hızlı cevap verdi.', '2023-03-16');
INSERT INTO listy.comment (author, comment, date) VALUES ('Arda', 'Web sitesi üzerinden sipariş vermek çok kolaydı.', '2023-03-17');
INSERT INTO listy.comment (author, comment, date) VALUES ('Ardam', 'Genel olarak alışverişimden çok memnunum.', '2023-03-18');
INSERT INTO listy.comment (author, comment, date) VALUES ('Tolga', 'Kalite ve fiyat dengesi mükemmeldi.', '2023-03-19');
INSERT INTO listy.comment (author, comment, date) VALUES ('LEMİNA', 'Satın alma işlemi sorunsuz gerçekleşti.', '2023-03-20');

INSERT INTO listy.comment (author, comment, date) VALUES ('Arda', 'Ürün açıklamaları gerçeği yansıtıyordu, tatmin oldum.', '2023-03-21');
INSERT INTO listy.comment (author, comment, date) VALUES ('Ardam', 'Teslimat süresi beklentimin altındaydı.', '2023-03-22');
INSERT INTO listy.comment (author, comment, date) VALUES ('Tolga', 'Siparişimi zamanında aldım, teşekkürler.', '2023-03-23');
INSERT INTO listy.comment (author, comment, date) VALUES ('LEMİNA', 'Ürünün kalitesi fiyatına çok uygundu.', '2023-03-24');
INSERT INTO listy.comment (author, comment, date) VALUES ('Arda', 'Web sitesinin tasarımı modern ve kullanışlıydı.', '2023-03-25');
INSERT INTO listy.comment (author, comment, date) VALUES ('Ardam', 'Ürün hakkındaki tüm bilgiler netti.', '2023-03-26');
INSERT INTO listy.comment (author, comment, date) VALUES ('Tolga', 'Müşteri hizmetlerinden aldığım destek harikaydı.', '2023-03-27');
INSERT INTO listy.comment (author, comment, date) VALUES ('LEMİNA', 'Siparişim sorunsuz şekilde kargoya verildi.', '2023-03-28');
INSERT INTO listy.comment (author, comment, date) VALUES ('Arda', 'Ürünü almaktan çok memnunum, tavsiye ederim.', '2023-03-29');
INSERT INTO listy.comment (author, comment, date) VALUES ('Ardam', 'Fiyat-performans oranı gerçekten başarılıydı.', '2023-03-30');

INSERT INTO listy.comment (author, comment, date) VALUES ('Tolga', 'Sipariş takip sistemi gayet kullanışlıydı.', '2023-03-31');
INSERT INTO listy.comment (author, comment, date) VALUES ('LEMİNA', 'Ürünün dayanıklılığı beklentilerimi aştı.', '2023-04-01');
INSERT INTO listy.comment (author, comment, date) VALUES ('Arda', 'Alışveriş sırasında hiçbir sorun yaşamadım.', '2023-04-02');
INSERT INTO listy.comment (author, comment, date) VALUES ('Ardam', 'Ürün ambalajı sağlam ve özenliydi.', '2023-04-03');
INSERT INTO listy.comment (author, comment, date) VALUES ('Tolga', 'Ürünün kalitesi beklediğimden daha iyiydi.', '2023-04-04');
INSERT INTO listy.comment (author, comment, date) VALUES ('LEMİNA', 'Satın alma süreci hızlı ve sorunsuzdu.', '2023-04-05');
INSERT INTO listy.comment (author, comment, date) VALUES ('Arda', 'Web sitesinden alışveriş yapmak keyifliydi.', '2023-04-06');
INSERT INTO listy.comment (author, comment, date) VALUES ('Ardam', 'Ürün açıklamalarında eksik bilgi yoktu.', '2023-04-07');
INSERT INTO listy.comment (author, comment, date) VALUES ('Tolga', 'Sipariş sonrası müşteri desteği çok başarılıydı.', '2023-04-08');
INSERT INTO listy.comment (author, comment, date) VALUES ('LEMİNA', 'Alışveriş deneyimimden tamamen memnunum.', '2023-04-09');

INSERT INTO listy.comment (author, comment, date) VALUES ('Arda', 'Fiyatlar oldukça rekabetçiydi.', '2023-04-10');
INSERT INTO listy.comment (author, comment, date) VALUES ('Ardam', 'Ürünün kalitesi tam da beklentilerime uygundu.', '2023-04-11');
INSERT INTO listy.comment (author, comment, date) VALUES ('Tolga', 'Teslimat hızı ve müşteri desteği harikaydı.', '2023-04-12');
INSERT INTO listy.comment (author, comment, date) VALUES ('LEMİNA', 'Sipariş süreci sorunsuz ve akıcı geçti.', '2023-04-13');
INSERT INTO listy.comment (author, comment, date) VALUES ('Arda', 'Ürün kalitesi ve fiyat dengesi çok iyiydi.', '2023-04-14');
INSERT INTO listy.comment (author, comment, date) VALUES ('Ardam', 'Alışveriş deneyimim genel olarak olumlu geçti.', '2023-04-15');
INSERT INTO listy.comment (author, comment, date) VALUES ('Tolga', 'Müşteri desteği ve hizmet kalitesi mükemmeldi.', '2023-04-16');
INSERT INTO listy.comment (author, comment, date) VALUES ('LEMİNA', 'Ürünü kullanmaya başladıktan sonra memnuniyetim arttı.', '2023-04-17');
INSERT INTO listy.comment (author, comment, date) VALUES ('Arda', 'Sipariş sonrası süreç oldukça başarılıydı.', '2023-04-18');
INSERT INTO listy.comment (author, comment, date) VALUES ('Ardam', 'Tekrar alışveriş yapmayı planlıyorum, teşekkürler.', '2023-04-19');